/*
 * Copyright 2018 Kaidan Gustave
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
@file:JvmName("Internal_HacksKt")
package me.kgustave.json.reflect.internal

// LOCATING KOTLIN-REFLECT IN CLASSPATH

// Have we found it yet?
private var foundKotlinReflectInClasspath = false

// Checks if kotlin-reflect is in the classpath.
//If it's not, we throw a KotlinReflectionNotSupportedError
internal fun checkIfReflectionIsInClasspath() {
    if(foundKotlinReflectInClasspath) return
    try { Class.forName("kotlin.reflect.jvm.internal.KClassImpl") } catch(e: ClassNotFoundException) {
        // Error message is generated by kotlin-reflect
        //as part of the no-args constructor.
        // In the future we might alter this to be more
        //informative towards our functions with the
        //library.
        throw KotlinReflectionNotSupportedError()
    }
    foundKotlinReflectInClasspath = true
}
